### ISSUE TITLE
No objects listing in custom scenes

### ISSUE THREAD

**Issue by Blitzman** [unrealcv/unrealcv#68]
Hi all!

I am trying to create my own scene with UE4 (4.12, compiled for Linux following the instructions) and UnrealCV (0.3) rather than just using the RealisticRendering cooked binary. I am just creating a blank project in which UE4 inserts a couple of chairs, a table, a statue, and two floor tiles.

I just choose the correct GameMode Override and run the scene. Then when sending the command to retrieve the list of objects (more specifically):

```
object_list_ = client.request('vget /objects').split(' ')
print("There are " + str(len(object_list_)) + " objects in this scene...")
print(object_list_)

```

I just get a list with a single 'ok' element like this:

```
There are 1 objects in this scene...
['ok']
```
The scene contains various static meshes so I don't know what could be causing this problem. That makes impossible to obtain object segmentation masks. I am able to get good RGB images, depth maps, and normal information.

I tried to find the RealisticRendering UE4 project to see if objects must be arranged in any special way but I was not able to find anything else than already compiled binaries.

If any of you knows what could be going on, I would be really grateful. I would also like to say thanks to the creators for such an awesome tool!

**Comment by qiuwch** [comment]
Can you try `vset /viewmode object_mask', 'vset /viewmode lit'. Then try 'vget /objects' again?
This looks like a very old bug.

**Comment by Blitzman** [comment]
Setting the viewmode to object_mask makes UE4 crash with the following output:
```

[2017.06.27-18.08.28:658][941]LogTemp:Warning: Request: 1:vset /viewmode object_mask
[2017.06.27-18.08.28:658][941]LogTemp:Warning: Receive message 1:vset /viewmode object_mask
[2017.06.27-18.08.28:658][941]LogTemp:Warning: Run SetMode object_mask
Assertion failed: PlayerController [File:/media/Work_SSD/qiuwch/workspace/UnrealEngine/HostProject/Plugins/UnrealCV/Source/UnrealCV/Private/PlayerViewMode.cpp] [Line: 127] 

[2017.06.27-18.08.28:659][941]LogLinux:Error: appError called: Assertion failed: Assertion failed: PlayerController [File:/media/Work_SSD/qiuwch/workspace/UnrealEngine/HostProject/Plugins/UnrealCV/Source/UnrealCV/Private/PlayerViewMode.cpp] [Line: 127] 


Signal 11 caught.
Malloc Size=131076 LargeMemoryPoolOffset=131092 
CommonLinuxCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=196655 
[2017.06.27-18.08.28:689][941]LogCrashTracker: 


[2017.06.27-18.08.28:690][941]LogLinux: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to access memory at address 0x00000003

[2017.06.27-18.08.28:690][941]LogLinux: Assertion failed: Assertion failed: PlayerController [File:/media/Work_SSD/qiuwch/workspace/UnrealEngine/HostProject/Plugins/UnrealCV/Source/UnrealCV/Private/PlayerViewMode.cpp] [Line: 127] 

```

**Comment by Blitzman** [comment]
Well, to add to the previous response: setting the viewmode from UE4 console works fine and object instances are shown properly. Setting the viewmode from Python using client.request('vset /viewmode object_mask') is what makes UE4 to crash.

**Comment by qiuwch** [comment]
It seems this line is failed. https://github.com/unrealcv/unrealcv/blob/7e7aebdb939ed166a14aa1965230396921ba0761/Source/UnrealCV/Private/PlayerViewMode.cpp#L137

When you run the game, can you check the tree view of the scene and find out which class type is the player? Is it a UE4CVPawn?

**Comment by qiuwch** [comment]
If the command in the editor is successful and the python client failed, then I expect the `vget /objects` in the editor can be successful after changing the view mode, is it right?

**Comment by Blitzman** [comment]
I have checked the tree view and the actor is the default one from the scene. I tried deleting it and adding a UE4CVPawn with the same outcome. UE4 crashes too when I try to execute the vset /viewmode object_mask and the vget /objects commands and both of them cause UE4 to crash again this time in UE4 editor.

Is there any guideline on how to create a custom scene? Maybe I am missing something.

**Comment by qiuwch** [comment]
This tutorial is something missing and we need to do. Let me try to write one tonight and I will ping you in this thread when I finish.

**Comment by Blitzman** [comment]
Thanks a lot, sounds awesome! Really looking forward to it :+1:

**Comment by qiuwch** [comment]
Hi, @Blitzman 

I wrote a tutorial here. http://docs.unrealcv.org/en/master/plugin/custom_scene.html

It seems there is nothing you need to change, changing the GameMode to UE4CVGameMode is needed for a reason that the camera for the object_mask is of a different height than the Game viewport, but not essential. 

I might need to test v0.3.0 with UE412 to reproduce your issue. Is it possible for you to share your UE4 project to do the diagnosis?

**Comment by Blitzman** [comment]
Hi @qiuwch, your efforts are very much appreciated! I will give it a shot compiling UE4.14 and using UnrealCV 0.3.9 as you specified in that tutorial and let you know the result ASAP. In case it does not work I will share the project to do the diagnosis!

Thank you very much!

**Comment by Blitzman** [comment]
@qiuwch I detected some inconsistencies between the documentation here (http://unrealcv.org/tutorial/plugin.html#linux) and the tutorial. The first one suggests to use UE4.12 since there are compatibility issues on later versions, however, your tutorial makes use of UE4.14. I am trying to compile UE4.14 on my Linux machine and I am having trouble when applying the OpenEXR patch:

```
albert@galactica:~/Downloads/UnrealEngine-4.14$ git apply 0001-Fix-openexr-support-for-linux-version.patch
error: patch failed: Engine/Source/Runtime/ImageWrapper/ImageWrapper.Build.cs:20
error: Engine/Source/Runtime/ImageWrapper/ImageWrapper.Build.cs: patch does not apply
```

Is the OpenEXR issue already fixed on UE4.14 or is there anything else messing up with the patch? How did you deal with it on your machine?

**Comment by Blitzman** [comment]
@qiuwch Any idea about the patch issues with 4.14? Thanks!

**Comment by qiuwch** [comment]
Hi, @Blitzman Sorry I forgot to reply this. 

You don't need the exr patch for v0.3.9, it is encouraged to use the new npy version, which doesn't depend on the exr patch, see a demo here http://docs.unrealcv.org/en/master/tutorials/generate_images_tutorial.html.

**Comment by Blitzman** [comment]
Hi @qiuwch,

I tried the tutorial again, compiled UE4.14 and the last UnrealCV 0.3.9 successfully. Then a new error arises... when I follow it and try to get a depth map like this:
`
res = client.request('vget /camera/0/depth npy')`

, the following error shows up.


```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/albert/miniconda3/envs/py-3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/albert/miniconda3/envs/py-3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/albert/miniconda3/envs/py-3.6/lib/python3.6/site-packages/unrealcv/__init__.py", line 197, in __receiving
    message = SocketMessage.ReceivePayload(self.socket)
  File "/home/albert/miniconda3/envs/py-3.6/lib/python3.6/site-packages/unrealcv/__init__.py", line 88, in ReceivePayload
    return payload.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 2: invalid start byte
```

I tried doing it like this:
res = client.request('vget /camera/0/depth depth.npy')`

but then this happens with npyio:
```

Traceback (most recent call last):
  File "demo.py", line 279, in <module>
    frames.append(render_frame(client, pos))
  File "demo.py", line 230, in render_frame
    depth = clip_real_depthmap(read_npy(client.request('vget /camera/0/depth depth.npy')), 0.0, 8.0), # The depth is saved as HDR image
  File "demo.py", line 17, in read_npy
    return np.load(io.StringIO(res))
  File "/home/albert/miniconda3/envs/py-3.6/lib/python3.6/site-packages/numpy/lib/npyio.py", line 405, in load
    fid.seek(-min(N, len(magic)), 1)  # back-up
OSError: Can't do nonzero cur-relative seeks
```

Did you ever face this kind of issue?

Thanks!
Albert.

**Comment by qiuwch** [comment]
There are some fixes for python3 has not been pushed to pypi yet.

**Comment by qiuwch** [comment]
You can try cd client/python, `pip install -e .`  and install the version in this folder.

**Comment by doublerebel** [comment]
I can't reproduce this with Python 3.6.3 on Windows, with current UnrealCV and Unreal Engine 4.18.2.  The command works for me.
